### ISSUE TITLE
ML functions

### ISSUE THREAD

**Issue by jaelim** [Microsoft/DMTK#3]
Hi, Thanks for the great open source library. I was wondering if there are popular machine learning methods in DMTK that I can try such as random forest, SVM, KNN, PLS, NN, Tree Bagging, etc.?

**Comment by feiga** [comment]
@jaelim Hi, currently DMTK only contains LDA and word embedding.

**Comment by taifeng1205** [comment]
@jaelim, hi, DMTK team is working very hard to push more algorithm into this took kit, we will soon release some algorithms you mentioned above.

**Comment by taifeng1205** [comment]
one we have boosting tree. welcome to have a try. For NN, we are collaborating with CNTK, and help them to improve the distributed deep learning training.
