### ISSUE TITLE
Support for Docker

### ISSUE THREAD

**Issue by loretoparisi** [Microsoft/DMTK#5]
Please add Dockerfile to support docker install.

**Comment by loretoparisi** [comment]
@chivee Hello, please clarify your action?

**Comment by chivee** [comment]
will moving issues to application repos

**Comment by chivee** [comment]
@loretoparisi , could you clarify which docker file are you requested for? For lightLDA and mutiverso applications please refer to https://github.com/Microsoft/DMTK/wiki/Run-in-docker

**Comment by loretoparisi** [comment]
@chivee thank you.
